### ISSUE TITLE
Warning when leaving editor-mode

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#184]
We need a **warning:** when you edited the code in the editor and you click back to 'block-screen' 
you lose all the edits you made in the code. 
So a little warning like:  'Do you want to save the changes you made?'

And also a dialogue box: like an instruction / verwachtingsmanagement:
Blocks become code, but it doesn't work the other way around 
Blokken worden code, maar het werkt niet andersom.

**Comment by paulleaphy** [comment]
Couple of questions @Roelandsmith: When do you want instruction to appear? When you switch to the code editor? Every time? This might get annoying to users. It's possible to add a checkbox: "Never show this again". This would add a bit of complexity of course, so would take a bit longer to program.

**Comment by Roelandsmith** [comment]
Good point.
You want it when two things are TRUE:

- User is switching back to the Block-editor.
- User has non-saved changes in their code-screen code.

And -indeed- also a check-box 'don't show this again' would be great way to avoid annoyance.
But that checkbox for now we can choose to postpone .
It's a enhancement.

**Comment by paulleaphy** [comment]
Notes to self: 
- When the code editor is created, set it with the blockly-generated code if present, otherwise use the initial value of the code editor `code`, which should contain the default program
- Only set the `originalCode` field when saving, or loading a code project
- If the user intends to switch back to the blockly editor and `hasChanges` is true, show the dialog
- Give the user the options to continue to blockly editor, or remain in code editor
