### ISSUE TITLE
bij 1.2.1 pre 5 - blokken worden niet actief

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#224]
![image](https://user-images.githubusercontent.com/38002592/194564178-91787ac3-308c-4dbf-8453-81c243cf2f5c.png)

**Comment by paulsiersma** [comment]
Hi Roeland,

Thanks for testing, and submitting a bug! I am unfortunately unable to reproduce this behaviour on my machine. To properly fix this bug, some more information would be really helpful. Could you provide it using the template below? To accommodate non-Dutch speaking contributors, English is preferred.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by koen1711** [comment]
Closed due to inactivity.
