### ISSUE TITLE
bij 1.2.1 pre 5 - uploadknop blijft hangen

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#225]
uploaden loopt vast
programma afsluiten is noodzakelijk. Gebeurt vrij regelmatig

![image](https://user-images.githubusercontent.com/38002592/194564523-2fca7633-e76b-42c5-b051-b6bb46e2e486.png)

**Comment by paulsiersma** [comment]
Hi Roeland, 

Thanks for testing, and submitting a bug! To properly fix this bug, some more information would be really helpful. Could you provide it using the template below? To accommodate non-Dutch speaking contributors, English is preferred. 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by koen1711** [comment]
Closed due to inactivity, also this seems to be an issue related to a pre version which I assume is fixed.
