### ISSUE TITLE
Arduino Uno modus - driver installation dialogue not launched

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#72]
Situation:
user picks 'Arduino Uno'option in start screen.
building program and clicking 'Upload'
When uploading error occurs: 'Robot not found'

After that we choose Leaphy Original-platform.
Then dialogue appears: 'Driver installation needed'
After that everything works fine.

Solution:
'installation driver-function' needs to work in Arduino Uno modus also!

**Comment by paulsiersma** [comment]
There is nothing in the code related to driver installation that distinguishes between the Arduino UNO robot type and the Leaphy Original robot type. It's also really pretty hard to reproduce, because once the driver is installed, it's hard to uninstall it in a way that will retrigger the driver installation dialog. 

Maybe this was an incidental occurence? I don't see what I could do to fix this issue. @Roelandsmith feel free to reopen if you have new insights.
